services:

  vpn:
    image: lscr.io/linuxserver/wireguard
    container_name: vpn
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERPORT=51820
      - LOG_CONFS=true
    volumes:
      - ./vpnConfig:/config # Re-generate sample keys via /keys/generate.sh and put them into configs before use
    ports:
      - 51820:51820/udp
    restart: unless-stopped
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1


  # proxy:
  #   image: denisnovac/wstunnel
  #   container_name: proxy
  #   ports:
  #     - 443:443
  #   command: ["/bin/sh", "-c", "exec /home/app/wstunnel server  wss://[::]:443"]

